module.exports = {
   LOGIN_FORM: "LOGIN_FORM",
   SIGNUP_FORM: "SIGNUP_FORM",
   CREATE_TRACK_FORM: "CREATE_TRACK_FORM",
   EDIT_TRACK_FORM: "EDIT_TRACK_FORM",
   EDIT_USER_FORM: "EDIT_USER_FORM"
};
