module.exports = {
  RECEIVE_TRACK: "RECEIVE_TRACK",
  RECEIVE_TRACKS: "RECEIVE_TRACKS",
  RECEIVE_CURRENT_TRACK: "RECEIVE_CURRENT_TRACK",
  PAUSE_CURRENT_TRACK: "PAUSE_CURRENT_TRACK",
  PLAY_CURRENT_TRACK: "PLAY_CURRENT_TRACK",
  REMOVE_TRACK: "REMOVE_TRACK",
  SET_WAVEFORM: "SET_WAVEFORM"
};
