# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ceaba6be9eef00b9018ae583ef0a768aaab5cb9d85665d0674664b4eb3c986460aa2db2e8e4a8108c95f16aa43e8deb24a3048adc054e1e8277a0e7b236cf26a

test:
  secret_key_base: 2303d1a00d016e28411de6125c0874bc1e51c5463929903db34d12419684c361c91294a1f3bc6fc6739bb3f57562aa0e09877f454e16f7ef1a6d18d3f9039f9c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
